sudo: required
services:
  - docker
before_install:
  - docker build -t ajmeraabhishek/complex-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ajmeraabhishek/complex-client npm run test -- --coverage

after_success:
  - docker build -t ajmeraabhishek/complex-client  ./client
  - docker build -t ajmeraabhishek/complex-server  ./server
  - docker build -t ajmeraabhishek/complex-worker  ./worker
  - docker build -t ajmeraabhishek/complex-nginx  ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ajmeraabhishek/complex-client
  - docker push ajmeraabhishek/complex-server
  - docker push ajmeraabhishek/complex-worker
  - docker push ajmeraabhishek/complex-nginx

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: complex-dockers
  env: ComplexDockers-env
  bucket_name: elasticbeanstalk-us-west-2-456149911266
  bucket_path: complex-dockers
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

